model_names:
  - Random Forest
  - XGBoost
  - LightGBM
  - CatBoost
  - SVM

optuna_trials: 30
experiment_name: churn_model_optimization
mlflow_tracking_uri: https://dagshub.com/Niair/Customer_Churn_Prediction_using_MLOpps_MLflow_AWS_CI-CD.mlflow
