RandomForestClassifier:
  class: sklearn.ensemble.RandomForestClassifier
  params:
    n_estimators: [100, 200]
    max_depth: [5, 10]
    min_samples_split: [2, 5]

XGBClassifier:
  class: xgboost.XGBClassifier
  params:
    n_estimators: [100, 200]
    max_depth: [3, 6]
    learning_rate: [0.01, 0.1]

CatBoostClassifier:
  class: catboost.CatBoostClassifier
  params:
    iterations: [100, 200]
    learning_rate: [0.03, 0.1]
    depth: [4, 6]
    verbose: 0

GradientBoostingClassifier:
  class: sklearn.ensemble.GradientBoostingClassifier
  params:
    n_estimators: [100, 150]
    learning_rate: [0.05, 0.1]
    max_depth: [3, 5]