model_params:
  RandomForest:
    n_estimators: [100, 300]
    max_depth: [3, 10]
    min_samples_split: [2, 10]
    min_samples_leaf: [1, 10]
  CatBoost:
    iterations: [100, 500]
    depth: [4, 10]
    learning_rate: [0.01, 0.3]
    l2_leaf_reg: [0.001, 10.0]
  XGBoost:
    n_estimators: [100, 500]
    learning_rate: [0.01, 0.3]
    max_depth: [3, 10]
    subsample: [0.6, 1.0]
    colsample_bytree: [0.6, 1.0]
  SVC:
    C: [0.01, 100]
    kernel: ["linear", "rbf", "poly", "sigmoid"]
    degree: [2, 5]
  LogisticRegression:
    C: [0.01, 10.0]
    penalty: ["l1", "l2"]
  LightGBM:
    n_estimators: [100, 500]
    learning_rate: [0.01, 0.3]
    num_leaves: [31, 255]
    max_depth: [3, 10]